services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  db: