services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node-modules
    ports: 
      - 3000:3000
    stdin_open: true
    command: npm start
volumes:
  node_modules: