version: '3.3'

services:
  app:
    container_name: 'express-jwt-mongo'
    build: .
    volumes:
      - .:/example-jwt-express
      - node_modules:/example-jwt-express/node-modules
    ports: 3000:3000
    stdin_open: true
    command: npm run dev
volumes:
  node_modules: